### ISSUE TITLE
"We avoid development releases because netplay requires versions to match exactly for two users to play together."

### ISSUE THREAD

**Issue by blunelsongamer** [flathub/org.DolphinEmu.dolphin-emu#204] opened 2024-07-26 14:48 UTC
Moments later, flathub then released an dev release days ago. Please go back to beta, lmfao

**Comment by ColinKinloch** [comment] 2024-07-26 15:00
It may have been a good idea to have the dolphin achievements "dev" branch on the flatpak beta branch and keep stable tracking upstream "beta".

**Comment by blunelsongamer** [comment] 2024-07-26 18:07
Okay. It's strange, which I hope it can be fixed whatever a new beta haves been released or not.

I follow this, it works so it does really help.
https://github.com/flathub/org.DolphinEmu.dolphin-emu/issues/203#issuecomment-2239538189

**Comment by cpba** [comment] 2024-07-26 19:41
Duplicate of #203

**Closed by cpba** 2024-07-26 19:41 UTC
Labels: duplicate
