### ISSUE TITLE
Pointer and controls disable when tab out and tab back in

### ISSUE THREAD

**Issue by Ocarinaoftime** [flathub/org.DolphinEmu.dolphin-emu#168] opened 2023-10-30 23:26 UTC
Whenever I tab out of the game and tab back in, the pointer and the buttons don’t work anymore for some reason.

**Comment by cpba** [comment] 2023-11-05 17:15
I haven't been able to reproduce this.

At any rate, it doesn't seem like it would have anything to do with the flatpak build, it sounds like some quirk with the window manager not properly returning focus.

Did it work in some earlier release of the flatpak?
Do you use some esoteric desktop environment?
 Is there something else that might be grabbing the focus when you tab back in?
Does it only happen in fullscreen mode?

**Comment by Ocarinaoftime** [comment] 2023-11-05 17:25
I found a solution. I just enabled render game in main window and it is fixed.

**Comment by cpba** [comment] 2023-11-05 20:30
Alright then, I'm closing the issue.

**Closed by cpba** 2023-11-05 20:30 UTC

**Comment by LuaGunsX** [comment] 2024-06-10 21:21
I have the same problem with the Wii menu. And I have no idea how to render it in the main window.

**Comment by LuaGunsX** [comment] 2024-06-10 21:24
Nevermind, also tried rendering it, but that does not work.

**Comment by cpba** [comment] 2024-06-11 08:05
This has been hard to reproduce, so far it looks like some issue with newer
qt versions on some older compositors.

Are you using some uncommon desktop environment?

El dl., 10 de juny 2024, 23:25, LuaGunsX ***@***.***> va
escriure:

**Comment by Ocarinaoftime** [comment] 2024-06-11 10:25
i’m on a chromebook

**Comment by LuaGunsX** [comment] 2024-06-19 20:19
@cpba I'm on Cinammon 6.0.4.
