### ISSUE TITLE
[Bug] Connecting Real Wiimotes not working

### ISSUE THREAD

**Issue by nchristopher** [flathub/org.DolphinEmu.dolphin-emu#66] opened 2021-05-13 16:05 UTC
I was trying to connect a real Wiimote to this Flatpak version of Dolphin, but it wouldn't connect.

While I *could* get it to connect by passing through my Bluetooth adapter, it wouldn't connect if I choose to "Emulate the Wii's Bluetooth adapter" & selected "Real Wii Remote" as the first Wiimote.

I then compiled the normal Dolphin version from source (using [this guide](https://dolphin-emu.org/docs/guides/building-dolphin-linux)), and I didn't run into this issue.

This seems to be a bug specific to this Flatpak version of Dolphin. I'm not sure what the actual issue is, or how it can be fixed, so I hope someone else can figure out what's happening.

**Comment by nchristopher** [comment] 2021-05-13 18:09
This might be an issue with the `5.0-13963` build of Dolphin, which is what this Flatpak is currently using. There's a newer beta build of Dolphin available - `5.0-14095` - which might fix this issue, as [this message](https://dolphin-emu.org/update/latest/beta/) was left in that build's changelog: 

> Hey everyone, we don't have a Dolphin Progress Report this month, but it's come to our attention that last month's build had some very annoying regressions.  The "Real Wii Remote" option was instantly disconnecting Wii Remotes [...] Considering how many people use our beta builds [...], these regressions were unacceptable to leave unfixed. We're sorry to have to push an impromptu update, but these problems were severe enough that we felt it necessary to do so immediately.

**Comment by cpba** [comment] 2021-05-14 20:49
@nchristopher For clarity in case we're testing different things, when you say "pairing Real Wii Remotes", are you talking about using the bluetooth passthrough feature? or do you mean something else?

**Comment by nchristopher** [comment] 2021-05-14 22:09
Bluetooth Passthrough works fine after adding a udev rule, as described in [this wiki page](https://wiki.dolphin-emu.org/index.php?title=Bluetooth_Passthrough#Linux).

The issue is with pairing Real Wii Remotes when emulating the Wii's bluetooth adapter. Eg. a configuration like this one:
![image](https://user-images.githubusercontent.com/58091943/118336214-12fc9700-b4c6-11eb-8ce1-5d21e7c7d694.png)

When using the non-flatpak version of Dolphin, compiled from source using [this guide](https://dolphin-emu.org/docs/guides/building-dolphin-linux/), I can successfully pair Real Wiimotes using the above configuration. But when using the Flatpak version of Dolphin, the wiimote doesn't connect.

**Comment by cpba** [comment] 2021-05-15 08:55
Thank you, I was confused because bluetooth passthrough is one of the things I manually test before every release, but I have tested this other method now and I couldn't get it to work.

I realize now that perhaps older issues like #44 may have been talking about this other feature but were misinterpreted.

@nchristopher do you know if this has ever worked on a past release?

**Comment by nchristopher** [comment] 2021-05-15 16:07
I downgraded to commit 3b3d19bc2556b3008531f367634f7cc4065580ea, then to commit 96ac00b41aa368aa08038cc87e2032534cd44bc7 - I had the same issues on both of these builds. I only started using Dolphin's Flatpak a month or so ago, so I can't say whether it has ever worked.

**Comment by ColinKinloch** [comment] 2021-06-06 14:03
I got "Passthrough a Bluetooth adapter" working with a real wiimode with the current build (5.0-14095).

It took a while. Sometimes the emulator would stall when trying to take control of the dongle and I'd have to force stop emulation.

Toggling bluetooth in the gnome settings and running `sudo systemctl restart bluetooth` a few times got it working.

I assume this is an issue with dolphin itself rather than the flathub build.

If you're getting an `LIBUSB_ERROR_ACCESS` message then make sure you have the [udev rules](https://wiki.dolphin-emu.org/index.php?title=Bluetooth_Passthrough#Linux) configured correctly.

**Comment by cpba** [comment] 2021-06-06 21:12
@ColinKinloch "Passthrough a Bluetooth adapter" is a separate feature that already works.

This issue is for a different feature, you'll find it selecting the radiobutton labelled "Emulate the wii's bluetooth adapter" -> and then choosing "Real wii remote" on the dropdown menu.

**Comment by cpba** [comment] 2021-06-07 14:55
@nchristopher a new build fixing this issue will be available on flathub in a few minutes.

I'm closing it now because I've tested it to work on my system, but feel free to reopen it if you can somehow still reproduce it on your side.

**Closed by cpba** 2021-06-07 14:55 UTC
Labels: help wanted

**Comment by nchristopher** [comment] 2021-06-07 20:20
This feature works perfectly for me now.

Thank you @cpba and @ColinKinloch so much!
